//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orion.Framework.DataLayer.NH.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConventionFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConventionFormats() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orion.Framework.DataLayer.NH.Properties.ConventionFormats", typeof(ConventionFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a _.
        /// </summary>
        internal static string ColumnNameSeparator {
            get {
                return ResourceManager.GetString("ColumnNameSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Key.
        /// </summary>
        internal static string DefaultForeignKeyColumnSuffix {
            get {
                return ResourceManager.GetString("DefaultForeignKeyColumnSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IdKey.
        /// </summary>
        internal static string ElementKeyColumnName {
            get {
                return ResourceManager.GetString("ElementKeyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Value.
        /// </summary>
        internal static string ElementValueColumnName {
            get {
                return ResourceManager.GetString("ElementValueColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FK__{0}__{1}.
        /// </summary>
        internal static string ForeignKeySourceTarget {
            get {
                return ResourceManager.GetString("ForeignKeySourceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FK__{0}__{1}__{2}.
        /// </summary>
        internal static string ForeignKeySourceTargetKey {
            get {
                return ResourceManager.GetString("ForeignKeySourceTargetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}__{1}__{2}__FK.
        /// </summary>
        internal static string ForeignKeySourceTargetKeySuffix {
            get {
                return ResourceManager.GetString("ForeignKeySourceTargetKeySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}__{1}__FK.
        /// </summary>
        internal static string ForeignKeySourceTargetSuffix {
            get {
                return ResourceManager.GetString("ForeignKeySourceTargetSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}{1}.
        /// </summary>
        internal static string ManyToManyNoSeparator {
            get {
                return ResourceManager.GetString("ManyToManyNoSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}To{1}.
        /// </summary>
        internal static string ManyToManyToSeparator {
            get {
                return ResourceManager.GetString("ManyToManyToSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}_{1}.
        /// </summary>
        internal static string ManyToManyUndescoreSeparator {
            get {
                return ResourceManager.GetString("ManyToManyUndescoreSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}_{1}.
        /// </summary>
        internal static string RelationshipUnderscoreSeparated {
            get {
                return ResourceManager.GetString("RelationshipUnderscoreSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}_s.
        /// </summary>
        internal static string SourceColumnName {
            get {
                return ResourceManager.GetString("SourceColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}_t.
        /// </summary>
        internal static string TargetColumnName {
            get {
                return ResourceManager.GetString("TargetColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0}_.
        /// </summary>
        internal static string UnderscoreSuffix {
            get {
                return ResourceManager.GetString("UnderscoreSuffix", resourceCulture);
            }
        }
    }
}
