using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Framework.DataLayer.NHibernate.Loquacious.Convention
{
    /// <summary>
    /// Defines the conventions used when mapping many to many relationships to database table names
    /// </summary>
    public enum ManyToManyTableNamingConvention
    {
        /// <summary>
        /// Table name is generated by appending the first table name and the second table name separated by the underscore char
        /// </summary>
        FirstTableName_SecondTableName,
        
        /// <summary>
        /// Table name is generated by appending the first table name and the second table name separated by the 'To' prep.
        /// </summary>
        FirstTableNameToSecondTableName,

        /// <summary>
        /// Table name is composed by the first table name appended to the second table name
        /// </summary>
        FirstTableNameSecondTableName,

        /// <summary>
        /// A user defined convention
        /// </summary>
        Custom
    }
}
