//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orion.Framework.Web.Blazor.Components.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orion.Framework.Web.Blazor.Components.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numeric input only. Allowed are digits, culture specific number separator, digits separator, and negative sign..
        /// </summary>
        internal static string ParsingErrorMessageFormat {
            get {
                return ResourceManager.GetString("ParsingErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires a cascading parameter of type {1}. For example, you can use {2} inside an {3}.&quot;.
        /// </summary>
        internal static string RequiresCascadingParameterFormat {
            get {
                return ResourceManager.GetString("RequiresCascadingParameterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} too many digits entered. Max number of digits is.
        /// </summary>
        internal static string TooManyDigitsErrorMessageFormat {
            get {
                return ResourceManager.GetString("TooManyDigitsErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not a supported numeric type..
        /// </summary>
        internal static string TypeIsNotASupportedNumericTypeFormat {
            get {
                return ResourceManager.GetString("TypeIsNotASupportedNumericTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} unable to parse the input into a valid number. Please check your input..
        /// </summary>
        internal static string UnableToParseInputIntoANumberFormat {
            get {
                return ResourceManager.GetString("UnableToParseInputIntoANumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to or greater than zero. Value was {1}..
        /// </summary>
        internal static string ValueMustBeEqualToOrGreaterThanZeroFormat {
            get {
                return ResourceManager.GetString("ValueMustBeEqualToOrGreaterThanZeroFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} numeric input only. Allowed are digits, culture specific number separator, and negative sign..
        /// </summary>
        internal static string WholeNumberParsingErrorMessageFormat {
            get {
                return ResourceManager.GetString("WholeNumberParsingErrorMessageFormat", resourceCulture);
            }
        }
    }
}
